# version: "3.9"

services:
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+psycopg2://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    env_file:
      - .env
    restart: always
    user: postgres
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

# Optional secrets configuration (uncomment if used)
# secrets:
#   db-password:
#     file: db/password.txt
